runtime: custom
env: flex
entrypoint: streamlit run main.py --server.port=8080 --server.enableCORS=false

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.6
